api:
  build: .
  command: bin/inbox-api
  links:
    - mysql
    - redis
  ports:
    - "127.0.0.1:5555:5555"
  env_file:
    - env_sync

sync:
  build: .
  command: bin/inbox-start
  links:
    - mysql
    - redis
  env_file:
    - env_sync

redis:
  image: redis

mysql:
  # FIXME: create-db currently breaks on mysql 5.6 (the thread.subject index is
  # too large when using utf8mb4.)
  image: mysql:5.5
  env_file:
    - env_sync
